name: NPM CI

on:
  push:
    branch:
      - master
    paths:
      - "package.json"

jobs:
  validate:
    name: Validate Generation
    runs-on: ubuntu-latest
    steps:
      - name: Ensure Go
        uses: actions/setup-go@master
        with:
          go-version: 1.13.x

      - name: Ensure Node
        uses: actions/setup-node@master
        with:
          node-version: 12.x

      - name: Ensure protoc
        uses: roleypoly/actions/setup-protoc@master
        with:
          protoc-version: "3.9.1"

      - uses: actions/checkout@v1

      - name: Fetch Dependencies & Generate
        run: |
          export PATH=$PATH:$(go env GOPATH)/bin
          go get github.com/golang/protobuf/protoc-gen-go
          npm i
          go generate

      - name: Check if dirty
        run: test -z "`git status -s`" || (git status && exit 1)

  publish:
    name: Build & Publish
    runs-on: ubuntu-latest
    needs: validate
    steps:
      - uses: actions/checkout@v1

      - name: Publish (NPM)
        uses: actions/npm@master
        with:
          args: publish --access public
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
      
      - name: Publish (GitHub)
        uses: actions/npm@master
        with:
          args: publish --access public --registry https://npm.pkg.github.com/
        env:
          NPM_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
