name: NPM CI

on:
  push:
    branch:
      - master

jobs:
  validate:
    name: Validate Generation
    runs-on: ubuntu-latest
    steps:
      - name: Ensure Go
        uses: actions/setup-go@master
        with:
          go-version: 1.13.x

      - uses: actions/checkout@v1

      - name: Generate
        run: go generate

      - name: Check Diff
        run: git diff --exit-code

  publish:
    name: Build & Publish
    runs-on: ubuntu-latest
    needs: validate
    steps:
      - uses: actions/checkout@v1

      - name: Publish
        uses: actions/npm@master
        with:
          args: publish --access public
          env:
            NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
