on:
  push:
    branch:
      - !master
  pull_request:
    branch:
      - "*"

jobs:
  validate:
    name: Validate Generation
    runs-on: ubuntu-latest
    steps:
      - name: Ensure Go
        uses: actions/setup-go@master
        with:
          go-version: 1.13.x

      - uses: actions/checkout@v1

      - name: Generate
        run: go generate

      - name: Check Diff
        run: git diff --exit-code
